### ISSUE TITLE
Does the performance difference of the graphics card change the result?

### ISSUE THREAD

**Issue by HumanKR** [SoonbeomChoi/BEGAN-Sing#3]
(I'm using GTX 970)

Learning is done to epoch500
So I just listen latest_G_little_star and...
I can't hear it something like language. maybe sound like noise.
https://drive.google.com/file/d/12c6GVAXj-dO1x9pGvaPgKg14hcqEmR0d/view?usp=sharing
like this.

and then, i Inference it using your pretrained to epoch400.
wow. it's seem's like korean now. she's singing. that's a good result.
I learned epoch 500 but that's a only 400.
what is problem...

or the batch_size change the result?
I'm not have enough VRAM so i just change to 8 (I tried to change data_mode to multi but, still cuda out of memory)

**Comment by SoonbeomChoi** [comment]
The performance difference between the pretrained model and a model trained with 'sample_dataset' is not due to any hyper-parameter changes like batch size. 'sample_dataset' is just a sample to show how a dataset should be structured to train a model. The pretrained model is trained with 50 songs. You should collect your own dataset following the structure like 'sample_dataset'. 

But don't worry we are ready to release the full dataset used for pretrained model in the following repo, CSD dataset (https://github.com/SoonbeomChoi/emotiontts_open_db/tree/master/CSD).

**Comment by HumanKR** [comment]
Oh it was 50 songs...
I was think 'sample_dataset' is for exactly what you said but I also thought it is possible to just for test only 1 songs.
On second thought, that was a ridiculous question. heh

And you released datasets...??????? ohhhhhhh I wasn't know this!!
Aww... Thank you for helping a little dumb student... yea me.
